W 15125668.separate read write pool
salesforce/carbonj pull request #853
Opened 2024-04-01 18:07 UTC by peterzxu-crm

2024-04-04 17:21 UTC, sholavanalli commented on carbonj.service/src/main/java/com/demandware/carbonj/service/db/index/IndexStoreRocksDB.java
> +                log.error("Failed to sync with primary DB {} - {}", dbDir.getAbsolutePath(), e.getMessage(), e);
Emit a metric here so that we can setup alerts?

2024-04-05 12:43 UTC, sholavanalli requested changes

2024-04-05 12:43 UTC, sholavanalli commented on carbonj.service/src/main/java/com/demandware/carbonj/service/db/util/FileUtils.java
> +            log.info("Creating directory {}", parent.getAbsolutePath());
Make it debug

2024-04-05 12:43 UTC, sholavanalli commented on carbonj.service/src/main/java/com/demandware/carbonj/service/db/util/FileUtils.java
> +        log.info("Dumping queue with {} elements into file {}", lines.size(), file.getAbsoluteFile());
Same as above

2024-04-05 12:47 UTC, sholavanalli commented
Please add info to README on this new feature and the config parameters explaining what each config does.

2024-04-09 15:09 UTC, peterzxu-crm commented
> Please add info to README on this new feature and the config parameters explaining what each config does.

I will update README when I am doing real CarbonJ shard per [W-15397829](https://gus.lightning.force.com/a07EE00001neJbYYAU)

2024-04-09 18:25 UTC, sholavanalli approved these changes

2024-04-09 19:24 UTC, merged